title: ClickHelper
description: 一个可以辅助操作的小工具.
show_downloads: true
show_logs: true


log:
  url: /clickhelper-app/log-page

download:
  url: http://ota.micform.com/helper/3/micform-helper-v1.0.2-230527113113-release.apk

google_analytics:
theme: jekyll-theme-cayman